// <auto-generated />
using System;
using AutoMatch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoMatch.Migrations
{
    [DbContext(typeof(AutoMatchContext))]
    [Migration("20251108163720_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoMatch.Models.Administrador", b =>
                {
                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<int>("Id_Admin")
                        .HasColumnType("int");

                    b.HasKey("Id_User");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("AutoMatch.Models.Anuncio", b =>
                {
                    b.Property<int>("Id_Anuncio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Anuncio"));

                    b.Property<int>("AdministradorId_User")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ano")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Admin")
                        .HasColumnType("int");

                    b.Property<int>("Id_Modelo")
                        .HasColumnType("int");

                    b.Property<int>("Id_Vendedor")
                        .HasColumnType("int");

                    b.Property<int>("Kilometros")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("ModeloId_Modelo")
                        .HasColumnType("int");

                    b.Property<int>("Preco")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Anuncio");

                    b.HasIndex("AdministradorId_User");

                    b.HasIndex("Id_Vendedor");

                    b.HasIndex("ModeloId_Modelo");

                    b.ToTable("Anuncios");
                });

            modelBuilder.Entity("AutoMatch.Models.CodigoPostal", b =>
                {
                    b.Property<string>("Codigo_Postal")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Codigo_Postal");

                    b.ToTable("CodigoPostais");
                });

            modelBuilder.Entity("AutoMatch.Models.Compra", b =>
                {
                    b.Property<int>("Id_Compra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Compra"));

                    b.Property<DateTime>("Data_Compra")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Anuncio")
                        .HasColumnType("int");

                    b.Property<int>("Id_Comprador")
                        .HasColumnType("int");

                    b.HasKey("Id_Compra");

                    b.HasIndex("Id_Anuncio");

                    b.HasIndex("Id_Comprador");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("AutoMatch.Models.Comprador", b =>
                {
                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<string>("Codigo_Postal")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Contactos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_User");

                    b.HasIndex("Codigo_Postal");

                    b.ToTable("Compradores");
                });

            modelBuilder.Entity("AutoMatch.Models.DadosFaturacao", b =>
                {
                    b.Property<int>("Dados_Faturacao_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dados_Faturacao_Id"));

                    b.Property<string>("Fatura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id_Vendedor")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Dados_Faturacao_Id");

                    b.HasIndex("Id_Vendedor");

                    b.ToTable("DadosFaturacoes");
                });

            modelBuilder.Entity("AutoMatch.Models.Documento", b =>
                {
                    b.Property<int>("Id_Doc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Doc"));

                    b.Property<string>("CaminhoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id_Anuncio")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Doc");

                    b.HasIndex("Id_Anuncio");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("AutoMatch.Models.Imagens", b =>
                {
                    b.Property<int>("Id_Imagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Imagem"));

                    b.Property<string>("CaminhoImagem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id_Anuncio")
                        .HasColumnType("int");

                    b.HasKey("Id_Imagem");

                    b.HasIndex("Id_Anuncio");

                    b.ToTable("Imagens");
                });

            modelBuilder.Entity("AutoMatch.Models.Modelo", b =>
                {
                    b.Property<int>("Id_Modelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Modelo"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Combustivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeModelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Transmissao")
                        .HasColumnType("bit");

                    b.HasKey("Id_Modelo");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("AutoMatch.Models.Notificacoes", b =>
                {
                    b.Property<int>("Id_notificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_notificacao"));

                    b.Property<DateTime>("Data_Envio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Comprador")
                        .HasColumnType("int");

                    b.Property<int>("Id_Vendedor")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_notificacao");

                    b.HasIndex("Id_Comprador");

                    b.HasIndex("Id_Vendedor");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("AutoMatch.Models.Preferencias", b =>
                {
                    b.Property<int>("Preferencias_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Preferencias_Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Detalhe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id_Comprador")
                        .HasColumnType("int");

                    b.HasKey("Preferencias_Id");

                    b.HasIndex("Id_Comprador");

                    b.ToTable("Preferencias");
                });

            modelBuilder.Entity("AutoMatch.Models.Reserva", b =>
                {
                    b.Property<int>("Id_Reserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Reserva"));

                    b.Property<DateTime>("Data_Fim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Anuncio")
                        .HasColumnType("int");

                    b.Property<int>("Id_Comprador")
                        .HasColumnType("int");

                    b.HasKey("Id_Reserva");

                    b.HasIndex("Id_Anuncio");

                    b.HasIndex("Id_Comprador");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("AutoMatch.Models.Utilizador", b =>
                {
                    b.Property<int>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_User"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_User");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("AutoMatch.Models.Vendedor", b =>
                {
                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<string>("CodigoPostalCodigo_Postal")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Codigo_Postal")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Contactos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NIF")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Tipo")
                        .HasColumnType("bit");

                    b.HasKey("Id_User");

                    b.HasIndex("CodigoPostalCodigo_Postal");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("AutoMatch.Models.Visita", b =>
                {
                    b.Property<int>("Id_Visita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Visita"));

                    b.Property<DateTime>("Data_Hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Reserva")
                        .HasColumnType("int");

                    b.HasKey("Id_Visita");

                    b.HasIndex("Id_Reserva");

                    b.ToTable("Visitas");
                });

            modelBuilder.Entity("AutoMatch.Models.Administrador", b =>
                {
                    b.HasOne("AutoMatch.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("AutoMatch.Models.Anuncio", b =>
                {
                    b.HasOne("AutoMatch.Models.Administrador", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorId_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoMatch.Models.Vendedor", "Vendedor")
                        .WithMany("Anuncios")
                        .HasForeignKey("Id_Vendedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoMatch.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId_Modelo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("Modelo");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("AutoMatch.Models.Compra", b =>
                {
                    b.HasOne("AutoMatch.Models.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("Id_Anuncio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoMatch.Models.Comprador", "Comprador")
                        .WithMany()
                        .HasForeignKey("Id_Comprador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("AutoMatch.Models.Comprador", b =>
                {
                    b.HasOne("AutoMatch.Models.CodigoPostal", "CodigoPostal")
                        .WithMany()
                        .HasForeignKey("Codigo_Postal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoMatch.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CodigoPostal");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("AutoMatch.Models.DadosFaturacao", b =>
                {
                    b.HasOne("AutoMatch.Models.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("Id_Vendedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("AutoMatch.Models.Documento", b =>
                {
                    b.HasOne("AutoMatch.Models.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("Id_Anuncio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anuncio");
                });

            modelBuilder.Entity("AutoMatch.Models.Imagens", b =>
                {
                    b.HasOne("AutoMatch.Models.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("Id_Anuncio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anuncio");
                });

            modelBuilder.Entity("AutoMatch.Models.Notificacoes", b =>
                {
                    b.HasOne("AutoMatch.Models.Comprador", "Comprador")
                        .WithMany()
                        .HasForeignKey("Id_Comprador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoMatch.Models.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("Id_Vendedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("AutoMatch.Models.Preferencias", b =>
                {
                    b.HasOne("AutoMatch.Models.Comprador", "Comprador")
                        .WithMany()
                        .HasForeignKey("Id_Comprador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("AutoMatch.Models.Reserva", b =>
                {
                    b.HasOne("AutoMatch.Models.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("Id_Anuncio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoMatch.Models.Comprador", "Comprador")
                        .WithMany()
                        .HasForeignKey("Id_Comprador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("AutoMatch.Models.Vendedor", b =>
                {
                    b.HasOne("AutoMatch.Models.CodigoPostal", "CodigoPostal")
                        .WithMany()
                        .HasForeignKey("CodigoPostalCodigo_Postal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoMatch.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CodigoPostal");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("AutoMatch.Models.Visita", b =>
                {
                    b.HasOne("AutoMatch.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("Id_Reserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("AutoMatch.Models.Vendedor", b =>
                {
                    b.Navigation("Anuncios");
                });
#pragma warning restore 612, 618
        }
    }
}
